from bank_common import *

def populate(b):
 tangents(b);practical(b)

def tangents(b):
 F=r'y-y_0=f^\prime(x_0)(x-x_0),\quad k=\tan\alpha,\quad k_{\text{норм}}=-1/f^\prime(x_0)'
 # id, printed curve, requested result, field descriptors, first step, key step, final explanation.
 rows=[
 (1,r'y=\sin2x','Найди все точки с касательной, параллельной y=2x.',[field('x','Абсцисса через k ∈ ℤ','pi*k','expression',variables=['k']),field('y','Ордината','0')],r'y^\prime=2\cos2x=2',r'\cos2x=1\Rightarrow x=\pi k',r'(\pi k;0),\quad k\in\mathbb Z'),
 (2,r'y=x+\sin x','Найди все точки с горизонтальной касательной.',[field('x','Абсцисса через k ∈ ℤ','(2*k+1)*pi','expression',variables=['k']),field('y','Ордината через k ∈ ℤ','(2*k+1)*pi','expression',variables=['k'])],r'y^\prime=1+\cos x=0',r'x=(2k+1)\pi,\quad\sin x=0',r'((2k+1)\pi;(2k+1)\pi)'),
 (4,r'y=x^2,\quad x_1=1,\ x_2=3','Касательная параллельна секущей через указанные точки. Найди точку касания.',[field('points','Точка (x;y)','(2;4)','points')],r'k_{\text{сек}}=(9-1)/(3-1)=4',r'2x=4\Rightarrow x=2',r'(2;4)'),
 (5,r'y=x^2(x-2)^2','Найди все точки с горизонтальными касательными.',[field('points','Точки: (x;y) | (x;y)','(0;0)|(1;1)|(2;0)','points')],r'y^\prime=4x(x-1)(x-2)',r'y^\prime=0\Rightarrow x=0,1,2',r'(0;0),\ (1;1),\ (2;0)'),
 (6,r'y=1/(1+x^2)','Найди точку с горизонтальной касательной.',[field('points','Точка (x;y)','(0;1)','points')],r'y^\prime=-2x/(1+x^2)^2',r'y^\prime=0\Rightarrow x=0',r'(0;1)'),
 (7,r'y=1/x','Касательные параллельны y=−x/4+3. Найди точки касания.',[field('points','Все точки','(2;1/2)|(-2;-1/2)','points')],r'y^\prime=-1/x^2=-1/4',r'x^2=4\Rightarrow x=\pm2',r'(2;1/2),\ (-2;-1/2)'),
 (8,r'y=x^3-px,\quad x_0=1,\ M(2;3)','Найди p, при котором касательная в x=1 проходит через M.',[field('p','Параметр p','1/2')],r'y_0=1-p,\quad k=3-p',r'3-(1-p)=(3-p)(2-1)\Rightarrow 2p=1',r'p=1/2'),
 (9,r'y=e^x+e^{-x}','Найди точку с касательной, параллельной y=3x/2.',[field('points','Точка','(ln(2);5/2)','points')],r'e^x-e^{-x}=3/2',r'u=e^x>0:\quad 2u^2-3u-2=0\Rightarrow u=2',r'(\ln2;5/2)'),
 (10,r'y=\sqrt{3x+1}','Найди точку с касательной, параллельной y=3x/4.',[field('points','Точка','(1;2)','points')],r'y^\prime=3/(2\sqrt{3x+1})',r'3/(2\sqrt{3x+1})=3/4\Rightarrow x=1',r'(1;2)'),
 (11,r'y=-3x^2+2,\quad x_0=1','Найди касательную и площадь треугольника с осями координат.',[field('line','Касательная: y=…','y=-6x+5','lines'),field('area','Площадь','25/12')],r'y_0=-1,\quad k=-6',r'y+1=-6(x-1);\quad (0;5),\ (5/6;0)',r'y=-6x+5,\quad S=\tfrac12\cdot5\cdot5/6=25/12'),
 (12,r'y=3x^3+4,\quad x_0=2','Найди ординату пересечения касательной с Oy.',[field('value','Ордината','-44')],r'y_0=28,\quad k=36',r'y=28+36(x-2)=36x-44',r'-44'),
 (13,r'y=x^2/2-3x+1','Найди касательную с углом наклона 45° к положительному направлению Ox.',[field('line','Касательная','y=x-7','lines')],r'k=\tan(\pi/4)=1',r'x-3=1\Rightarrow x_0=4,\ y_0=-3',r'y=x-7'),
 (14,r'y=2x^2-4x+3','Найди касательные в точках пересечения с y=x+3.',[field('lines','Обе касательные','y=-4x+3; y=6x-19/2','lines')],r'2x^2-4x+3=x+3\Rightarrow x=0,5/2',r'y^\prime=4x-4;\quad k_1=-4,\ k_2=6',r'y=-4x+3,\quad y=6x-19/2'),
 (15,r'y=5x^3-1,\quad x_0=1','Найди ординату пересечения касательной с Oy.',[field('value','Ордината','-11')],r'y_0=4,\quad k=15',r'y=4+15(x-1)=15x-11',r'-11'),
 (16,r'y=2x^2-1,\quad x_0=1','Найди касательную и площадь треугольника с осями.',[field('line','Касательная','y=4x-3','lines'),field('area','Площадь','9/8')],r'y_0=1,\quad k=4',r'y=4x-3;\quad (0;-3),\ (3/4;0)',r'S=\tfrac12\cdot3\cdot3/4=9/8'),
 (17,r'y=x^2-3x+5','Касательная параллельна y=4x+13. Найди абсциссу касания.',[field('x','Абсцисса','7/2')],r'y^\prime=2x-3',r'2x-3=4',r'x=7/2'),
 (18,r'y=x^3/3-3x^2/2-9x+8','Найди все x, где касательная имеет угол наклона 45° к Ox.',[field('x','Абсциссы через ;','-2;5','set')],r'y^\prime=x^2-3x-9',r'x^2-3x-9=1\Rightarrow(x-5)(x+2)=0',r'x=-2,5'),
 (19,r'y=x^2-6x+3,\quad x_0=2','Найди касательную и площадь треугольника с осями.',[field('line','Касательная','y=-2x-1','lines'),field('area','Площадь','1/4')],r'y_0=-5,\quad k=-2',r'y=-2x-1;\quad(0;-1),\ (-1/2;0)',r'S=\tfrac12\cdot1\cdot1/2=1/4'),
 (20,r'y=x^2-4x+3','Найди углы наклона касательных в пересечениях с Ox. Углы в (0,π), радианы.',[field('angles','Оба угла через ;','pi-arctan(2);arctan(2)','set')],r'y=0\Rightarrow x=1,3',r'y^\prime=2x-4\Rightarrow k_1=-2,\ k_2=2',r'\alpha_1=\pi-\arctan2,\quad\alpha_2=\arctan2'),
 (32,r'f(x)=x^3-x-1,\quad g(x)=3x^2-4x+1','Найди точки с параллельными касательными при ОДИНАКОВОЙ абсциссе.',[field('f','Точка на f','(1;-1)','points'),field('g','Точка на g','(1;0)','points')],r'f^\prime=3x^2-1,\quad g^\prime=6x-4',r'3x^2-1=6x-4\Rightarrow3(x-1)^2=0',r'(1;-1),\ (1;0)'),
 (33,r'y=1+\ln x','Найди a, при котором прямая y=ax−2 касается графика.',[field('a','Параметр a','e^2')],r'a=1/x_0,\quad 1+\ln x_0=ax_0-2',r'1+\ln x_0=-1\Rightarrow x_0=e^{-2}',r'a=e^2'),
 (34,r'y=\frac{4^x-2^{x+1}}{\ln4}','Найди точки с касательной, параллельной y=2x+5.',[field('points','Точка','(1;0)','points')],r'y^\prime=4^x-2^x=2',r'u=2^x>0:\quad u^2-u-2=0\Rightarrow u=2',r'(1;0)'),
 (36,r'y=e^{x/2},\quad x=2','Найди острый угол пересечения графика с вертикальной прямой. Радианы.',[field('angle','Угол','arctan(2/e)')],r'y^\prime(2)=e/2',r'\alpha=\pi/2-\arctan(e/2)=\arctan(2/e)',r'\alpha=\arctan(2/e)'),
 (37,r'y=x^2+bx+c','Парабола касается y=x в M₀(1;1). Найди b и c.',[field('b','b','-1'),field('c','c','1')],r'1+b+c=1,\quad 2+b=1',r'b=-1,\quad c=-b',r'b=-1,\ c=1'),
 (38,r'y=\frac{x-4}{x-2}','Покажи параллельность касательных в пересечениях с осями. Введи их общий угловой коэффициент.',[field('k','Общий коэффициент','1/2')],r'(4;0),\ (0;2);\quad y^\prime=2/(x-2)^2',r'y^\prime(4)=y^\prime(0)=1/2',r'k=1/2'),
 (39,r'y=x^2-4x+5,\quad x-y+1=0','Нормали в пересечениях с прямой и хорда образуют треугольник. Найди площадь.',[field('area','Площадь','15/4')],r'x^2-4x+5=x+1\Rightarrow x=1,4;\quad A(1;2),B(4;5)',r'n_A:y=x/2+3/2,\quad n_B:y=-x/4+6;\quad C(6;9/2)',r'S=\frac12|\det(B-A,C-A)|=15/4'),
 (40,r'y=x^2-6x+6','Составь нормаль, перпендикулярную прямой от начала координат к вершине параболы.',[field('line','Нормаль','y=x-21/4','lines')],r'V(3;-3),\quad k_{OV}=-1,\quad k_n=1',r'-1/(2x_0-6)=1\Rightarrow x_0=5/2,\ y_0=-11/4',r'y=x-21/4')]
 for i,prompt,desc,fields,first,key,last in rows:
  task=b.fields(f'tangent-{i:02}',6,'Касательные и нормали',prompt,fields,four(F,first,key,r'\boxed{'+last+'}'),8 if i<=13 else 9 if i<=33 else 10,f'Банк · задача 8 · пример {i}',description=desc,instruction='Введи только запрошенные результаты в поля ниже.')
  if i==32:task['note']='В оригинале не оговорено равенство абсцисс. Здесь явно выбран этот учебный вариант; без него решений бесконечно много.';b.issue(task['id'],'Для однозначного варианта явно добавлено равенство абсцисс.')
  if i==39:task['note']='В PDF напечатано «x−y+1+0». Здесь явно прочитано как уравнение x−y+1=0.';b.issue(task['id'],'Опечатка в уравнении прямой: знак + перед 0 прочитан как = и явно отмечен.')
 for i,original in [(35,1)]:
  import copy
  task=copy.deepcopy(b.find(f'tangent-{original:02}'));task['id']=f'tangent-{i:02}';task['meta']=f'Банк · задача 8 · пример {i}';task['sources']=[source(10,f'Задача 8, пример {i}')];b.tasks.append(task)
 b.invalid('tangent-03',6,'Уточнение ориентированного угла',r'f(x)=\frac{x+2}{x-2},\quad\angle(\text{касательная},Oy)=-\pi/4','В источнике не указано направление отсчёта отрицательного угла от оси Oy.','Нужно уточнить соглашение об ориентированном угле; разные направления отсчёта дают разные условия на наклон касательной.',8,'Банк · задача 8 · пример 3')
 b.invalid('tangent-31',6,'Проверка концов дуги',r'y=2x-x^2,\quad A(1;1),\ B(-3;3)','На дуге AB требуется касательная, параллельная хорде AB.','Точка B не лежит на кривой: f(−3)=−15, а не 3. Поэтому указанной дуги AB этой кривой нет.',9,'Банк · задача 8 · пример 31',r'f(-3)=-6-9=-15\ne3')

def practical(b):
 # Reduced prose preserves all numerical conditions; original PDF is linked beside each card.
 def add(i,prompt,desc,fields,model,derivative,key,conclusion,formula=r'\text{Модель}\ \longrightarrow\ f^\prime=0\ \longrightarrow\ \text{проверка минимума/максимума}'):
  return b.fields(f'practical-{i:02}',10,'Практическая задача',prompt,fields,four(formula,model,derivative+r'\quad '+key,conclusion),10 if i<=5 else 11 if i<=13 else 12 if i<=22 else 13,f'Банк · задача 9 · пример {i}',description=desc,instruction='Введи итоговые значения. Единицы измерения указаны у полей.')
 add(1,r'C_{\text{топл}}=kv^3','При 10 км/ч топливо стоит 3000 руб./ч; остальные расходы 48000 руб./ч. Минимизируй расходы на 1 км и найди общие расходы в час.',[field('speed','Скорость, км/ч','20'),field('cost','Общие расходы, руб./ч','72000')],r'k=3000/10^3=3,\quad F(v)=3v^2+48000/v',r'F^\prime=6v-48000/v^2=0',r'v^3=8000;\quad F^{\prime\prime}>0',r'v=20,\quad C=3\cdot20^3+48000=72000')
 for i in [2,30]:add(i,r'h=9,\quad L=15,\quad v_{\text{вода}}=4,\ v_{\text{берег}}=5','Корабль в 9 км от ближайшей точки берега C, лагерь в 15 км по берегу. Где высадиться, чтобы минимизировать время? x — расстояние от C к лагерю.',[field('x','Расстояние от C к лагерю, км','12')],r'T(x)=\sqrt{81+x^2}/4+(15-x)/5,\quad0\le x\le15',r'T^\prime=x/(4\sqrt{81+x^2})-1/5',r'25x^2=16(81+x^2)\Rightarrow x=12;\quad T^{\prime\prime}>0',r'x=12\text{ км (до лагеря ещё 3 км)}')
 task=add(3,r'h=1.4,\quad a=1.8','Нижний край картины на 1,8 м выше глаз, высота 1,4 м. Найди расстояние от стены для наибольшего угла обзора.',[field('distance','Расстояние, м','2.4')],r'\alpha(x)=\arctan(3.2/x)-\arctan(1.8/x)',r'\alpha^\prime=-3.2/(x^2+3.2^2)+1.8/(x^2+1.8^2)',r'x^2=1.8\cdot3.2=5.76;\quad\alpha(0+)=\alpha(+\infty)=0',r'x=2.4\text{ м}')
 task['sources'] += [source(3,'№10, картина','demo'),source(16,'Задача о картине','solutions')]
 add(4,r'y_1=x^2/2,\quad y_2=\ln x','При каком x первая ордината возрастает в 4 раза быстрее второй?',[field('x','x','2')],r'y_1^\prime=4y_2^\prime',r'x=4/x,\quad x>0',r'x^2=4',r'x=2')
 add(5,r'AC=285,\quad BC=60,\quad v_1=52,\ v_2=20','Станция на железной дороге между A и ближайшей к B точкой C. Найди её расстояние от C в сторону A для наименьшего времени пути A→B.',[field('distance','Расстояние от C, км','25')],r'T(x)=(285-x)/52+\sqrt{x^2+3600}/20',r'T^\prime=-1/52+x/(20\sqrt{x^2+3600})',r'52x=20\sqrt{x^2+3600}\Rightarrow x=25;\quad T^{\prime\prime}>0',r'25\text{ км от C в сторону A}')
 add(6,r'P=l,\quad l>0','Проволока длиной l согнута в прямоугольник. Найди размеры с максимальной площадью.',[field('sides','Обе стороны: (a;b)','(l/4;l/4)','points',variables=['l'])],r'a+b=l/2,\quad S(a)=a(l/2-a)',r'S^\prime=l/2-2a=0',r'a=l/4,\quad S^{\prime\prime}=-2<0',r'(a;b)=(l/4;l/4)')
 add(7,r'a=27,\quad b=64','Два канала пересекаются под прямым углом. Найди наибольшую длину бревна, которое можно провести через поворот.',[field('length','Длина, м','125')],r'L(\theta)=27/\sin\theta+64/\cos\theta',r'L^\prime=-27\cos\theta/\sin^2\theta+64\sin\theta/\cos^2\theta',r'\tan^3\theta=27/64;\quad L\to\infty\text{ на концах}',r'L_{\min}=(27^{2/3}+64^{2/3})^{3/2}=125')
 add(8,r'R^\prime=10,\quad R=100','Радиус шара растёт на 10 см/с. Найди скорость роста объёма при R=100 см.',[field('rate','Скорость объёма, см³/с','400000*pi')],r'V=4\pi R^3/3',r'V^\prime=4\pi R^2R^\prime',r'4\pi\cdot100^2\cdot10',r'V^\prime=400000\pi')
 add(9,r'P_{\text{осн}}=8,\quad h=3','Прямоугольный параллелепипед: найди стороны основания для наибольшего объёма.',[field('sides','Стороны: (a;b), м','(2;2)','points')],r'a+b=4,\quad V=3a(4-a)',r'V^\prime=12-6a',r'a=2,\quad V^{\prime\prime}=-6<0',r'a=b=2')
 add(10,r'l=20','Коническая воронка с образующей 20 см. Найди высоту для максимального объёма.',[field('height','Высота, см','20/sqrt(3)')],r'r^2=400-h^2,\quad V=\pi h(400-h^2)/3',r'V^\prime=\pi(400-3h^2)/3',r'h=20/\sqrt3;\quad V(0)=V(20)=0',r'h=20/\sqrt3')
 temperatures=[(11,5*t**4/4-t**3/3-10*t*t+4*t+4,3),(12,-t**4/4+10*t**3/3-27*t*t/2+18*t+18,7),(13,t**4/4-2*t**3/3-8*t*t+32*t+32,5),(14,-t**4/4+3*t**3-23*t*t/2+15*t+15,6),(15,-t**4/4+8*t**3/3-17*t*t/2+10*t+10,6)]
 for i,f,end in temperatures:
  d=s.diff(f,t);critical=[v for v in s.solve(d,t) if v.is_real and 0<v<end];candidates=[s.Integer(0),s.Integer(end),*critical];values=[f.subs(t,v) for v in candidates];maximum=max(values,key=lambda v:float(v));rounded=int(s.floor(maximum+R(1,2)))
  table=r'\begin{array}{c|c}t&T(t)\\'+r'\\'.join(tex(v)+'&'+tex(s.N(f.subs(t,v),7)) for v in candidates)+r'\end{array}'
  add(i,'T(t)='+tex(f)+r',\quad t\in[0,'+str(end)+']','Найди наибольшую температуру на всём отрезке. Округли ответ до целого.',[field('temperature','Максимум, округлённый до целого',str(rounded))],r'T^\prime(t)='+tex(s.factor(d)),r'T^\prime=0\Rightarrow t\in\{'+','.join(tex(v) for v in critical)+r'\}',table,r'\max T\approx'+tex(s.N(maximum,10))+r'\Rightarrow\boxed{'+str(rounded)+'}',r'\max_{[a,b]}T=\max\{T(a),T(b),T(t_i):T^\prime(t_i)=0\}')
  b.verification.append({'id':f'practical-{i:02}','method':'all critical points and endpoints','passed':True,'result':str(rounded)})
 add(16,r'y=x^2,\quad M(2;1/2)','Найди ближайшую к M точку параболы. В ответе сумма её координат.',[field('sum','Сумма координат','2')],r'D^2=(x-2)^2+(x^2-1/2)^2',r'(D^2)^\prime=4(x^3-1)',r'x=1,\ y=1;\quad D^2\to\infty\text{ при }|x|\to\infty',r'x+y=2')
 add(17,r'P=16','Прямоугольник из проволоки длиной 16: найди наибольшую площадь.',[field('area','Площадь','16')],r'a+b=8,\quad S=a(8-a)',r'S^\prime=8-2a=0',r'a=b=4;\quad S^{\prime\prime}=-2',r'S=16')
 add(18,r'F(t)=t/(t+16)-t/25','Изученная доля минус забытая. Сколько дней готовиться для максимального результата?',[field('days','Дней','4')],r't\ge0,\quad F(t)=t/(t+16)-t/25',r'F^\prime=16/(t+16)^2-1/25',r't+16=20\Rightarrow t=4;\quad F^{\prime\prime}<0',r't=4')
 for i,minimum in [(19,False),(21,True)]:add(i,r'a+b=12,\quad a,b\ge0','Минимизируй сумму квадратов. В ответе произведение слагаемых.' if minimum else 'Максимизируй сумму квадратов. В ответе произведение слагаемых.',[field('product','Произведение','36' if minimum else '0')],r'Q(a)=a^2+(12-a)^2=2(a-6)^2+72',r'Q^\prime=4a-24,\quad Q^{\prime\prime}=4>0',r'\text{Минимум при }a=6;\quad\text{максимум на концах }a=0,12',r'ab=36' if minimum else r'ab=0')
 add(20,r'S=2\pi r^2+2\pi rh','Закрытая цилиндрическая банка: при заданной полной поверхности максимизируй объём. В ответе отношение диаметра к высоте.',[field('ratio','Диаметр / высота','1')],r'h=S/(2\pi r)-r,\quad V=Sr/2-\pi r^3',r'V^\prime=S/2-3\pi r^2=0',r'S=6\pi r^2\Rightarrow h=2r;\quad V^{\prime\prime}<0',r'2r/h=1')
 add(22,r'x^2/2-y^2=1,\quad M(3;0)','Найди ближайшие точки гиперболы. В ответе сумма модулей координат любой из них.',[field('sum','|x| + |y|','3')],r'D^2=(x-3)^2+y^2=3x^2/2-6x+8,\quad |x|\ge\sqrt2',r'(D^2)^\prime=3x-6',r'x=2,\quad y=\pm1;\quad\text{сравниваем обе ветви}',r'|2|+|\pm1|=3')
 add(23,r'a+b+c=54,\quad a=2b,\quad a,b,c>0','Максимизируй произведение. В ответе модуль разности наибольшего и наименьшего слагаемых.',[field('difference','Разность','12')],r'b=u,\ a=2u,\ c=54-3u;\quad P=2u^2(54-3u)',r'P^\prime=18u(12-u)',r'u=12;\quad (a,b,c)=(24,12,18);\quad P\to0\text{ на концах}',r'24-12=12')
 add(24,r'V=64,\quad a^2h=64','Закрытая коробка с квадратным основанием: найди размеры при наименьшей поверхности.',[field('dimensions','Размеры (a;a;h)','(4;4;4)','points')],r'S=2a^2+4ah=2a^2+256/a',r'S^\prime=4a-256/a^2',r'a^3=64,\quad a=h=4;\quad S^{\prime\prime}>0',r'(a;a;h)=(4;4;4)')
 add(25,r'A(1;2)','Прямая через A отсекает треугольник в первом координатном углу. Найди её наклон для минимальной площади.',[field('slope','Угловой коэффициент','-2')],r'x/u+y/v=1,\quad 1/u+2/v=1,\quad S=uv/2=u^2/(u-1)',r'S^\prime=u(u-2)/(u-1)^2,\quad u>1',r'u=2,\ v=4;\quad S\to\infty\text{ на концах области}',r'k=-v/u=-2')
 add(26,r'AB=17,\quad BC=8,\quad v_{\text{шоссе}}=5,\ v_{\text{поле}}=3','C — проекция B на шоссе. Найди расстояние от A до места поворота с шоссе в поле.',[field('distance','От A до поворота, км','9')],r'AC=\sqrt{17^2-8^2}=15,\quad T(x)=x/5+\sqrt{(15-x)^2+64}/3',r'T^\prime=1/5-(15-x)/(3\sqrt{(15-x)^2+64})',r'15-x=6;\quad T^{\prime\prime}>0',r'x=9')
 add(27,r'I=k\sin\varphi/r^2,\quad a>0','На какой высоте h над центром круглого стола радиуса a освещённость края максимальна?',[field('height','Высота через a','a/sqrt(2)','expression',variables=['a'])],r'r^2=a^2+h^2,\quad\sin\varphi=h/r,\quad I=kh/(a^2+h^2)^{3/2}',r'I^\prime=k(a^2-2h^2)/(a^2+h^2)^{5/2}',r'h=a/\sqrt2;\quad I(0)=I(+\infty)=0',r'h=a/\sqrt2')
 add(28,r'\text{Три доски одинаковой ширины }a','Желоб из трёх одинаковых досок. Найди острый угол боковой стенки к основанию для максимального сечения. Ответ в радианах.',[field('angle','Угол, радианы','pi/3')],r'S=a^2(1+\cos\theta)\sin\theta,\quad0<\theta\le\pi/2',r'S^\prime=a^2(2\cos^2\theta+\cos\theta-1)',r'\cos\theta=1/2;\quad S\text{ сначала растёт, затем убывает}',r'\theta=\pi/3')
 add(29,r'a+b=40','Прямоугольный треугольник с суммой катетов 40. Найди катеты для наибольшей площади.',[field('legs','Катеты: (a;b)','(20;20)','points')],r'S=a(40-a)/2',r'S^\prime=20-a',r'a=20,\ b=20;\quad S^{\prime\prime}=-1',r'(20;20)')
 add(31,r'\theta=kt^2,\quad T=8','Первый оборот за 8 с. Найди угловую скорость в t=32 с.',[field('omega','Угловая скорость, рад/с','2*pi')],r'k=2\pi/8^2=\pi/32',r'\omega=\theta^\prime=2kt',r'\omega(32)=2(\pi/32)32',r'\omega=2\pi')
 add(32,r'16x^2+9y^2=400','Ордината убывает с той же скоростью, с какой растёт абсцисса. Найди все точки.',[field('points','Все точки','(3;16/3)|(-3;-16/3)','points')],r'32x+18yy^\prime=0',r'y^\prime=-16x/(9y)=-1',r'y=16x/9\Rightarrow x=\pm3',r'(3;16/3),\ (-3;-16/3)')
 add(33,r'P_{\text{осев}}=6a,\quad a>0','Найди наибольший объём цилиндра с заданным периметром осевого сечения.',[field('volume','Объём через a','pi*a^3','expression',variables=['a'])],r'2(2r+h)=6a,\quad V=\pi r^2(3a-2r)',r'V^\prime=6\pi r(a-r)',r'r=a,\ h=a;\quad V=0\text{ на границах}',r'V_{\max}=\pi a^3')
 add(34,r'l>0','Найди наибольший объём конуса при фиксированной образующей l.',[field('volume','Объём через l','2*pi*l^3/(9*sqrt(3))','expression',variables=['l'])],r'V=\pi h(l^2-h^2)/3',r'V^\prime=\pi(l^2-3h^2)/3',r'h=l/\sqrt3,\quad r^2=2l^2/3;\quad V=0\text{ на концах}',r'V_{\max}=2\pi l^3/(9\sqrt3)')
 add(35,r'y=x^2,\quad y=2x-4','Найди точку N на параболе, наименее удалённую от прямой.',[field('points','Точка N','(1;1)','points')],r'd(x)=|x^2-2x+4|/\sqrt5=((x-1)^2+3)/\sqrt5',r'd^\prime=2(x-1)/\sqrt5',r'x=1,\ y=1;\quad d^{\prime\prime}>0',r'N(1;1)')
 task=b.add('demo-electric',10,'Сила тока по заряду',r'q(t)=2t^3-2t','1',four(r'I(t)=q^\prime(t)',r'I(t)=6t^2-2',r'6t^2-2=4\Rightarrow t^2=1,\quad t\ge0',r'\boxed{t=1\text{ с}}'),2,'Демо · №10 · ток',description='Найди момент после начала отсчёта, когда сила тока равна 4 А.',instruction='Введи время в секундах.');task['sources']=[source(3,'№10, электрический ток','demo')]
